package winx.bitirme.achievement.client.model;

public enum EnumAchievementType {
    LOGIN_INTO_ACCOUNT,
    USE3IN1_FOR_THREE_MONTHS,
    USE3IN1_FOR_ONE_YEAR,
    USE_CHAT_MODULE_FOR_100_HOURS,
    USE_SLEEP_MODULE_FOR_100_HOURS,
    USE_MEDITATION_MODULE_FOR_30_MINUTES_DAILY,
    USE_SLEEP_MODULE_FOR_8_HOURS_DAILY,
    COMPLETE_YOUR_SLEEP_GOAL_3_TIMES,
    COMPLETE_15_ITEMS_IN_TODO_LIST
}
